export enum UserRole {
  ADMIN = 'ADMIN',
  SUPERADMIN = 'SUPERADMIN',
  SITEENGINEER = 'SITEENGINEER',
  LEADENGINEER = 'LEADENGINEER',
  CUSTOMERCARE = 'CUSTOMERCARE',
  STOREKEEPER = 'STOREKEEPER',
  ACCOUNTANT = 'ACCOUNTANT',
  MANAGER = 'MANAGER',
  AGENT = 'AGENT',
  CLIENT = 'CLIENT',
  HR = 'HR',
  STAFF = 'STAFF',
}

export enum PropertyVisibility {
  PRIVATE = 'PRIVATE',
  PUBLIC = 'PUBLIC',
}

export enum UserGender {
  Male = 'Male',
  Female = 'Female',
}

export enum MessageContentType {
  TEXT = 'TEXT',
  IMAGE = 'IMAGE',
  FILE = 'FILE',
  MIXED = 'MIXED',
}

export enum SenderType {
  BUSINESS = 'BUSINESS',
  CUSTOMER = 'CUSTOMER',
}

export enum Department {
  MANAGEMENT = 'MANAGEMENT',
  ENGINEERING = 'ENGINEERING',
  TECHNICALSUPPORT = 'TECHNICAL SUPPORT',
  MARKETING = 'MARKETING',
}

export enum Audiance {
  ENGINEERS = 'ENGINEERS',
  CLIENTS = 'CLIENTS',
  AGENTS = 'AGENTS',
  STOREKEEPERS = 'STORE KEEPERS',
  PUBLIC = 'PUBLIC',
}

export enum NotificationCategory {
  NEWACCOUNT = 'NEWACCOUNT',
  CONTACT = 'CONTACT',
  NOTIFICATION = 'NOTIFICATION',
  STATUSCHANGE = 'STATUSCHANGE',
  LOGIN = 'LOGIN',
  CHAT = 'CHAT',
  MESSAGE = 'MESSAGE',
  OTP = 'OTP',
  STOCK = 'STOCK',
  GENERAL = 'GENERAL',
  BROADCAST = 'BROADCAST',
  BIRTHDAY = 'BIRTHDAY',
  HOLIDAY = 'HOLIDAY',
  ANNIVERSARY = 'ANNIVERSARY',
  PAYMENT = 'PAYMENT',
  INVESTMENT_APPLIED = 'INVESTMENT_APPLIED',
  INVESTMENT_APPROVED = 'INVESTMENT_APPROVED',
  INVESTMENT_REJECTED = 'INVESTMENT_REJECTED',
  INVESTMENT_PAYMENT_RECEIVED = 'INVESTMENT_PAYMENT_RECEIVED',
  INVESTMENT_EXPIRING_SOON = 'INVESTMENT_EXPIRING_SOON',
  INVESTMENT_EXPIRED = 'INVESTMENT_EXPIRED',
  INVESTMENT_SETTLED = 'INVESTMENT_SETTLED',
  INVESTMENT_EXTENDED = 'INVESTMENT_EXTENDED',
  SALE_CREATED = 'SALE_CREATED',
  SALE_APPLICATION = 'SALE_APPLICATION',
  SALE_APPROVED = 'SALE_APPROVED',
  SALE_PAYMENT = 'SALE_PAYMENT',
  SALE_COMPLETED = 'SALE_COMPLETED',
  SALE_APPLIED = 'SALE_APPLIED',
  SALE_PAYMENT_COMPLETED = 'SALE_PAYMENT_COMPLETED',
  SALE_PAYMENT_SUCCESSFUL = 'SALE_PAYMENT_SUCCESSFUL',
  PAYMENT_RECEIVED = 'PAYMENT_RECEIVED',
  PAYMENT_SUCCESSFUL = 'PAYMENT_SUCCESSFUL',
  PAYMENT_COMPLETED = 'PAYMENT_COMPLETED',
  PAYMENT_REVERSED = 'PAYMENT_REVERSED',
  PAYMENT_REFUND = 'PAYMENT_REFUND',
  NEWS = 'NEWS',
  PAYMENT_PLAN_CREATED = 'PAYMENT_PLAN_CREATED',
  QUERY_SENT = 'QUERY_SENT',
  QUERY_ACKNOWLEDGED = 'QUERY_ACKNOWLEDGED',
  QUERY_REVOKED = 'QUERY_REVOKED',
  SUSPENDED = 'SUSPENDED',
  SUSPENSION_REVOKED = 'SUSPENSION_REVOKED',
  SUSPENSION_COMPLETED = 'SUSPENSION_COMPLETED',
  ALLOCATION = 'ALLOCATION',
}

export enum NotificationPriority {
  HIGH = 'HIGH',
  MEDIUM = 'MEDIUM',
  LOW = 'LOW',
}

export enum DebtType {
  Payable = 'Payable',
  Receivable = 'Receivable',
}

export enum EstateType {
  COMMERCIAL = 'COMMERCIAL',
  RESIDENTIAL = 'RESIDENTIAL',
}

export enum PaymentStatus {
  PAID = 'PAID',
  UNPAID = 'UNPAID',
  PENDING = 'PENDING',
  PARTIALLYPAID = 'PARTIALLYPAID',
}

export enum SupplyStatus {
  SUPPLIED = 'SUPPLIED',
  PARTIALLYSUPPLIED = 'PARTIALLYSUPPLIED',
  PENDING = 'PENDING',
}

export enum PaymentMethod {
  PARTPAYMENT = 'Part Payment',
  FULLPAYMENT = 'Full Payment',
  CASH = 'CASH',
}

export enum PaymentType {
  PROPERTYFEE = 'PROPERTYFEE',
  FACILITYFEE = 'FACILITYFEE',
  WATERFEE = 'WATERFEE',
  ELECTRICITYFEE = 'ELECTRICITYFEE',
  SUPERVISIONFEE = 'SUPERVISIONFEE',
  AUTHORITYFEE = 'AUTHORITYFEE',
  OTHERFEE = 'OTHERFEE',
  INFRASTRUCTURECOST = 'INFRASTRUCTURECOST',
  AGENCYFEE = 'AGENCYFEE',
  GENERAL = 'GENERAL',
}

export enum SystemType {
  REAL_ESTATE = 'REAL_ESTATE',
  LAND_SALE = 'LAND_SALE',
  PROPERTY_MANAGEMENT = 'PROPERTY_MANAGEMENT',
  HYBRID = 'HYBRID',
}

export enum Currency {
  NGN = 'NGN',
}

export enum Channel {
  EMAIL = 'EMAIL',
  SMS = 'SMS',
  WHATSAPP = 'WHATSAPP',
  INAPP = 'INAPP',
}

export enum TargetType {
  BILL = 'BILL',
  INCIDENT = 'INCIDENT',
  FUNDREQUEST = 'FUNDREQUEST',
}

export enum PropertyType {
  PLOT = 'PLOT',
  HOUSE = 'HOUSE',
}

export enum TransactionType {
  DEBIT = 'DEBIT',
  CREDIT = 'CREDIT',
  ADJUSTMENT = 'ADJUSTMENT',
}

export enum StateStatus {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  AVAILABLE = 'AVAILABLE',
  UNAVAILABLE = 'UNAVAILABLE',
  SUSPENDED = 'SUSPENDED',
  BLOCKED = 'BLOCKED',
  TRASHED = 'TRASHED',
  UNSEEN = 'UNSEEN',
  SEEN = 'SEEN',
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  DECLINED = 'DECLINED',
  DELETED = 'DELETED',
  PAID = 'PAID',
  PARTIALLYPAID = 'PARTIALLYPAID',
  UNPAID = 'UNPAID',
  PAYING = 'PAYING',
  REPLIED = 'REPLIED',
  PURCHASED = 'PURCHASED',
  RELEASED = 'RELEASED',
  ALLOCATED = 'ALLOCATED',
  CANCELED = 'CANCELED',
  VALID = 'VALID',
  EXPIRED = 'EXPIRED',
  RESOLVED = 'RESOLVED',
  INPROGRESS = 'INPROGRESS',
  COMPLETED = 'COMPLETED',
  RESERVED = 'RESERVED',
  SOLD = 'SOLD',
  RESCHEDULED = 'RESCHEDULED',
  SETTLED = 'SETTLED',
  SUPPLIED = 'SUPPLIED',
  PARTIALLYSETTLED = 'PARTIALLYSETTLED',
  PENDINGSETTLEMENT = 'PENDINGSETTLEMENT',
  SUCCESS = 'SUCCESS',
  QUEUED = 'QUEUED',
  SENT = 'SENT',
  FAILED = 'FAILED',
  CLOSED = 'CLOSED',
  DELIVERED = 'DELIVERED',
  REJECTED = 'REJECTED',
  DUE = 'DUE',
  CANCELLED = 'CANCELLED',
  ACKNOWLEDGED = 'ACKNOWLEDGED',
  REVOKED = 'REVOKED',
  UPDATED = 'UPDATED',
  OFFERED = 'OFFERED',
}

export enum InvestmentDuration {
  MONTH = 'MONTH',
  QUARTER = 'QUARTER',
  HALF_YEAR = 'HALF_YEAR',
  YEAR = 'YEAR',
}

export enum ActionType {
  UPDATE = 'UPDATE',
  DELETE = 'DELETE',
  PASSWORDCHANGE = 'CHANGEPASSWORD',
  DECREASE = 'DECREASE',
  INCREASE = 'INCREASE',
  CREATE = 'CREATE',
  CANCEL = 'CANCEL',
  SETTLE = 'SETTLE',
  STATUS_UPDATE = "STATUS_UPDATE",
}

export enum AuthProvider {
  INTERNAL = 'INTERNAL',
  EXTERNAL = 'EXTERNAL',
}

export enum LocationType {
  ESTATE = 'ESTATE',
  LAYOUT = 'LAYOUT',
  STANDALONE = 'STANDALONE',
}

export enum OfferAudiance {
  PUBLIC = 'PUBLIC',
  AGENTS = 'AGENTS',
  CLIENTS = 'CLIENTS',
}

export enum OfferDiscountType {
  DISCOUNT_AMOUNT = 'DISCOUNT_AMOUNT',
  DISCOUNT_PERCENTAGE = 'DISCOUNT_PERCENTAGE',
  BONUS = 'BONUS',
}

export enum PaymentFrequency {
  MONTHLY = 'MONTHLY',
  WEEKLY = 'WEEKLY',
  QUARTERLY = 'QUARTERLY',
  YEARLY = 'YEARLY',
  CUSTOM = 'CUSTOM',
}

export enum AccountingBookType {
  PAYABLE = 'PAYABLE',
  RECEIVABLE = 'RECEIVABLE',
  CASH_BOOK = 'CASH_BOOK',
  PETTY_CASH = 'PETTY_CASH',
  SALES_ACCOUNT = 'SALES_ACCOUNT',
  PMS_SALES = 'PMS_SALES',
}

export enum VoucherStatus {
  DRAFT = 'DRAFT',
  POSTED = 'POSTED',
  CANCELLED = 'CANCELLED',
}


export enum PettyCashDirection {
  INCOME = 'INCOME',
  EXPENDITURE = 'EXPENDITURE',
}